server:
  port: ${SERVER_PORT:7030}

spring:
  jpa:
    database: ${DATABASE_TYPE:postgresql}
    database-platform: ${DATABASE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}

    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        # 4) Your default schema (optional if you include currentSchema in the URL)
        default_schema: ${CURRENT_SCHEMA:gateway_customer_service}

  datasource:
    url: ${MASTER_DB_URL:jdbc:postgresql://ep-divine-resonance-a12pm9wr-pooler.ap-southeast-1.aws.neon.tech:5432/neondb?currentSchema=gateway_customer_service}
    username: ${MASTER_DB_USER:neondb_owner}
    password: ${MASTER_DB_PASSWORD:npg_o0jRVsD6paht}

  liquibase:
    enabled: false


eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVER_URI:http://localhost:8761/eureka}

redis:
  host: ${REDIS_HOST:absolute-newt-26689.upstash.io}
  port: ${REDIS_PORT:6379}
  password: ${REDIS_PASSWORD:AWhBAAIjcDE3NmZlZGU0ZGFmZGI0MmE5YmFlYTE3NzNhNTcwYjEyZnAxMA}
  ssl:
    enabled: false
    ca: ${REDIS_SSL_CA:~}

logging:
  level:
    root: info

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
