server:
  port: ${SERVER_PORT:7030}

spring:
  jpa:
    database: ${DATABASE_TYPE:postgresql}
    database-platform: ${DATABASE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}

    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        # 4) Your default schema (optional if you include currentSchema in the URL)
        default_schema: ${CURRENT_SCHEMA:gateway_customer_service}

  datasource:
    url: ${MASTER_DB_URL:jdbc:postgresql://10.112.20.87:5432/postgres?currentSchema=gateway_customer_service}
    username: ${MASTER_DB_USER:postgres}
    password: ${MASTER_DB_PASSWORD:mysecretpassword}

  liquibase:
    enabled: false


eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVER_URI:http://localhost:8761/eureka}

redis:
  host: ${REDIS_HOST:172.16.229.212}
  port: ${REDIS_PORT:30079}
  password: ${REDIS_PASSWORD:~}
  ssl:
    enabled: false
    ca: ${REDIS_SSL_CA:~}

logging:
  level:
    root: info

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
